DROP DATABASE IF EXISTS compta
GO

CREATE DATABASE Compta;
GO

USE Compta;

CREATE TABLE Fournisseur
(
	ID INT PRIMARY KEY NOT NULL,
	Nom VARCHAR(50)
)


CREATE TABLE Article
(
	ID INT PRIMARY KEY,
	Ref VARCHAR(13),
	Designation  VARCHAR(255),
	Prix DECIMAL,
	Id_fou INT FOREIGN KEY REFERENCES Fournisseur(ID)
)

CREATE TABLE Bon
(
	ID INT PRIMARY KEY,
	Numero INT,
	Date_cmde DATETIME,
	Delai INT,
	Id_fou INT FOREIGN KEY REFERENCES Fournisseur(ID)
)


CREATE TABLE Compo
(
	ID INT PRIMARY KEY NOT NULL,
	QTE INT,
	Id_art INT FOREIGN KEY REFERENCES Article(ID),
	Id_bon INT FOREIGN KEY REFERENCES Bon(ID)

)
